import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { CaseStudyModal } from "../components/ui/case-study-modal";

const projects = [
    {
        id: "01",
        title: "AI Analytics SaaS Platform",
        category: "SaaS",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2940&auto=format&fit=crop",
    },
    {
        id: "02",
        title: "Startup Landing Page",
        category: "Startup",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
    },
    {
        id: "03",
        title: "Minimal Command Interface",
        category: "AI Product",
        image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2940&auto=format&fit=crop",
    },
    {
        id: "04",
        title: "Editorial Brand Layout",
        category: "Personal Brand",
        image: "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?q=80&w=2940&auto=format&fit=crop",
    },
    {
        id: "05",
        title: "Structured Case Blocks",
        category: "Agency",
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=2944&auto=format&fit=crop",
    },
    {
        id: "06",
        title: "Token Dashboard UI",
        category: "Web3",
        image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2832&auto=format&fit=crop",
    },
];

export function ArchitecturesPage() {
    const [selectedProject, setSelectedProject] = useState<typeof projects[0] | null>(null);

    return (
        <>
            <div className="w-full min-h-screen bg-black text-white pt-32 pb-24 overflow-hidden relative">

                {/* Background Subtle Glow */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-[600px] bg-[radial-gradient(ellipse_at_top,rgba(255,255,255,0.03)_0%,transparent_70%)] rounded-full blur-[100px] pointer-events-none" />

                <div className="container mx-auto px-6 max-w-7xl relative z-10">

                    {/* HERO SECTION */}
                    <div className="flex flex-col items-center justify-center text-center mb-24 lg:mb-32 mt-10">
                        <motion.h1
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
                            className="text-5xl md:text-7xl lg:text-8xl font-display font-medium tracking-tight text-white mb-6 leading-[1.1]"
                        >
                            AI-Crafted<br />Digital Experiences
                        </motion.h1>
                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.8, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
                            className="text-lg md:text-xl text-white/50 tracking-wide font-light max-w-2xl"
                        >
                            Every project engineered through intelligence.
                            <br />
                            <span className="text-xs uppercase tracking-[0.2em] font-medium text-white/30 mt-4 block">
                                Generated. Structured. Deployed.
                            </span>
                        </motion.p>
                    </div>

                    {/* SHOWCASE GRID */}
                    <div className="w-full flex flex-col mb-16">
                        <motion.div
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ duration: 1, delay: 0.3 }}
                            className="mb-12 border-b border-white/10 pb-4"
                        >
                            <p className="text-[10px] uppercase tracking-widest text-white/40 font-semibold">
                                Selected architectures generated by Aura.
                            </p>
                        </motion.div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 lg:gap-16">
                            {projects.map((project, index) => (
                                <motion.div
                                    key={project.id}
                                    initial={{ opacity: 0, y: 30 }}
                                    whileInView={{ opacity: 1, y: 0 }}
                                    viewport={{ once: false, margin: "-100px" }}
                                    transition={{ duration: 0.8, delay: (index % 2) * 0.1, ease: [0.16, 1, 0.3, 1] }}
                                    className="group relative cursor-pointer block"
                                    onClick={() => setSelectedProject(project)}
                                >
                                    {/* Card Wrapper */}
                                    <div className="relative w-full aspect-[4/3] rounded-2xl md:rounded-3xl border border-white/10 bg-[#050505] overflow-hidden transition-all duration-700 group-hover:border-white/20 group-hover:scale-[1.02] group-hover:shadow-[0_0_80px_rgba(255,255,255,0.03)]">

                                        {/* Top: Category Tag */}
                                        <div className="absolute top-6 left-6 z-20 px-3 py-1.5 bg-black/50 backdrop-blur-md rounded-full border border-white/10 text-[10px] uppercase tracking-widest text-white/70 font-medium">
                                            {project.category}
                                        </div>

                                        {/* Image Preview */}
                                        <div className="w-full h-full relative">
                                            {/* Placeholder gradient overlay to darken image slightly */}
                                            <div className="absolute inset-0 bg-black/40 mix-blend-multiply z-10 group-hover:bg-black/20 transition-colors duration-700" />
                                            <img
                                                src={project.image}
                                                alt={project.title}
                                                className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105"
                                            />
                                        </div>

                                        {/* Hover Overlay: View Architecture */}
                                        <div className="absolute inset-0 bg-black/60 backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-opacity duration-500 z-20 flex flex-col items-center justify-center">
                                            <span className="px-6 py-3 bg-white text-black text-sm font-semibold rounded-full translate-y-4 group-hover:translate-y-0 transition-all duration-500 delay-100">
                                                View Architecture →
                                            </span>
                                        </div>

                                    </div>

                                    {/* Bottom: Project Title */}
                                    <div className="mt-6 flex items-baseline justify-between">
                                        <h3 className="text-xl md:text-2xl font-display font-medium text-white tracking-wide group-hover:text-white/80 transition-colors duration-300">
                                            {project.title}
                                        </h3>
                                        <span className="text-xs font-mono text-white/30">{project.id}</span>
                                    </div>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                </div>
            </div>

            <CaseStudyModal
                isOpen={selectedProject !== null}
                onClose={() => setSelectedProject(null)}
                project={selectedProject}
            />
        </>
    );
}
